heat_networks_library/urls.py
""" импорт модулей """

from django.urls import path
from .views import index, HeatNetworksLibraryListView, PipeCreateView

app_name = "heat_networks_library"

urlpatterns = [
    # path("", index, name="index"),
    path("", HeatNetworksLibraryListView.as_view(), name="index"),
    path("add-pipe/", PipeCreateView.as_view(), name="add_pipe"),
]

ovhomelab/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views
from project.views import custom_page_not_found
from project.views import custom_permission_denied

handler403 = custom_permission_denied
handler404 = custom_page_not_found

urlpatterns = [
    path("link-page/", admin.site.urls),
    path("", include("project.urls")),
    path("library_ts/", include("heat_networks_library.urls")),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password-reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password-change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # path('projects/', include('project.urls'))
]

project/urls.py
""" импорт модулей """

from django.urls import path

from .views import (
    ProjectsListView,
    ProjectDetailView,
    ProjectEditView,
    ProjectDeleteView,
    ProjectCreateView,
    index,
)

app_name = "project"

urlpatterns = (
    path("", index, name="index"),
    path("projects/", ProjectsListView.as_view(), name="projects"),
    path("project/<int:pk>", ProjectDetailView.as_view(), name="project_detail"),
    path("project/edit/<int:pk>", ProjectEditView.as_view(), name="project_edit"),
    path(
        "project/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"
    ),
    path("project/create/", ProjectCreateView.as_view(), name="project-create"),
)

heat_networks_library/models.py
""" импорт еобходимых модулей """

from django.db import models
from django.contrib.postgres.fields import ArrayField


# Create your models here.
class Pipe(models.Model):
    """Клас трубы без изоляции"""

    name = models.CharField(max_length=255)  # улосвное обозначение
    nominal_diameter = models.IntegerField(
        blank=True, null=True
    )  # Номинальный диаметр DN, Ду
    outer_diameter = models.DecimalField(
        max_digits=10, decimal_places=2
    )  # Наружный диаметр dн
    wall_thickness = ArrayField(
        models.DecimalField(max_digits=4, decimal_places=2)
    )  # Список толщин стенок для данного диаметра s
    weight_per_meter = ArrayField(
        models.DecimalField(max_digits=6, decimal_places=2)
    )  # вес 1м трубы m
    quality_standard = models.CharField(
        max_length=100
    )  # Наименование ГОСТа трубы ГОСТ 8732-78

    def __str__(self) -> str:
        return str(self.name)

heat_networks_library/forms.py
from decimal import Decimal
from django import forms
from .models import Pipe


class PipeCreateForm(forms.ModelForm):
    weight_per_meter = forms.DecimalField(required=False, label="Вес 1м трубы m")
    class Meta:
        model = Pipe
        fields = [
            "nominal_diameter",
            "outer_diameter",
            "wall_thickness",
            "weight_per_meter",
            "quality_standard",
        ]
        labels = {
            "nominal_diameter": "Номинальный диаметр DN, Ду (может быть пустым)",
            "outer_diameter": "Наружный диаметр Ødн",
            "wall_thickness": "Список толщин стенок для данного диаметра s",
            "weight_per_meter": "Вес 1м трубы m",
            "quality_standard": "Наименование ГОСТа",
        }
    def clean_weight_per_meter(self):
        weight_per_meter = self.cleaned_data.get("weight_per_meter")
        if weight_per_meter is None:
            outer_diameter = self.cleaned_data.get("outer_diameter")
            wall_thickness = self.cleaned_data.get("wall_thickness")
            if outer_diameter and wall_thickness:
                return self.calculate_pipe_weights(outer_diameter, wall_thickness)
        return weight_per_meter
    
    def save(self, commit=True):
        instance = super(PipeCreateForm, self).save(commit=False)
        instance.weight_per_meter = self.cleaned_data["weight_per_meter"]
        instance.name = f"Труба Ø{self.cleaned_data['outer_diameter']} {self.cleaned_data['quality_standard']}"
        if commit:
            instance.save()
        return instance

    def calculate_pipe_weights(self, outer_diameter, wall_thickness):
        calculated_weight = []
        for thickness in wall_thickness:
            weight = Decimal(0.02466) * thickness * (outer_diameter - thickness)
            calculated_weight.append(weight)
        return calculated_weight

heat_networks_library/views.py
""" импорт модулей"""

from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    CreateView,
    ListView,
    # DetailView,
    # UpdateView,
    # DeleteView,
    # CreateView,
)
from django.urls import reverse_lazy
from heat_networks_library.forms import PipeCreateForm
from ovhomelab.utils import SuperuserRequiredMixin
from heat_networks_library.models import Pipe


# Create your views here.
def index(request):
    "return index.html"
    return render(request, "heat_networks_library/index.html")


class HeatNetworksLibraryListView(LoginRequiredMixin, ListView):
    login_url = "/login/"
    model = Pipe
    template_name = "heat_networks_library/pipe_list.html"
    context_object_name = "pipes"


class PipeCreateView(SuperuserRequiredMixin, CreateView):
    login_url = "/login/"
    model = Pipe
    form_class = PipeCreateForm
    template_name = "heat_networks_library/pipe_create.html"
    success_url = reverse_lazy("heat_networks_library:index")
    context_object_name = "pipes"

heat_networks_library/templates/heat_networks_library/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
  <h1>Hello from heat netwoks library index html</h1>
  {% if user.is_authenticated %}
    <p>privite text should be hidden</p>
  {% endif %}
{% endblock %}

heat_networks_library/templates/heat_networks_library/pipe_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <div class="col-6 mt-5">
        <div class="row text-center"><h2>Создать трубопровод</h2></div>

        <form method="post" class="mt-3 mb-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
            <button type="button" class="btn btn-light"><a href="{% url 'heat_networks_library:index' %}">Отменить</a></button>
        </form>

    </div>

{% endblock main %}

heat_networks_library/templates/heat_networks_library/pipe_list.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block main %}
<h1>Hello from heat netwoks library index html</h1>
{% if user.is_superuser %} {% comment %} heat_networks_library {% endcomment %}
<p>privite text should be hidden</p>
<a
  class="btn btn-primary"
  href="{% url 'heat_networks_library:add_pipe' %}"
  role="button"
  >Добавить трубу</a
>

{% endif %}
  <div class="list-group flex-row flex-wrap col-12">
    {% for pipe in pipes %}
    <div class="d-flex flex-column col-4 px-3">
      <div class="bg-ligh border rounded-3 shadow mt-2">
        <p
          class="list-group-item mb-0"
          data-bs-toggle="collapse"
          data-bs-target="#multiCollapse_pipe{{pipe.pk}}"
          aria-expanded="true"
          aria-controls="multiCollapse_pipe{{pipe.pk}}"
        >
          {{pipe.name}}
        </p>
      </div>
      <div class="collapse multi-collapse" id="multiCollapse_pipe{{pipe.pk}}">
        <div class="card card-body shadow-lg p-3 mb-5 bg-body rounded">
          {% if pipe.nominal_diameter %}
          <div
            class="p-2 bg-ligh border border-secondary rounded-3 shadow my-2"
          >
            Номинальный диаметр DN: {{pipe.nominal_diameter|floatformat}}
          </div>
          {% endif %}
          <div
            class="p-2 bg-ligh border border-secondary rounded-3 shadow my-2"
          >
            Наружный диаметр Ødн: {{pipe.outer_diameter|floatformat}}
          </div>
          <div
            class="p-2 bg-ligh border border-secondary rounded-3 shadow my-2"
          >
            Наименование ГОСТа: {{pipe.quality_standard}}
          </div>

          <div
            class="d-flex flex-row bg-ligh border border-secondary rounded-3 shadow my-2 p-2"
          >
            <div class="flex-column py-2 text-center me-2">
              <div class="mb-2 border-2 border-bottom border-secondary">№</div>
              {% for index in pipe.wall_thickness %}
              <div class="border-1 border-bottom border-secondary">
                {{ forloop.counter }}
              </div>
              {% endfor %}
            </div>

            <div class="flex-column py-2 text-center mx-2">
              <div class="mb-2 border-2 border-bottom border-secondary">
                Толщина стенки, мм
              </div>
              {% for thickness in pipe.wall_thickness %}
              <div class="border-1 border-bottom border-secondary">
                {{thickness|floatformat:2}}
              </div>
              {% endfor %}
            </div>

            <div class="flex-column py-2 text-center mx-2">
              <div class="mb-2 border-2 border-bottom border-secondary">
                Вес трубы, кг
              </div>
              {% for weight in pipe.weight_per_meter %}
              <div class="border-1 border-bottom border-secondary">
                {{weight|floatformat:2}}
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
</div>

{% endblock %}