ovhomelab/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views
from project.views import custom_page_not_found
from project.views import custom_permission_denied

handler403 = custom_permission_denied
handler404 = custom_page_not_found

urlpatterns = [
    path("link-page/", admin.site.urls),
    path("", include("project.urls")),
    path("library_ts/", include("heat_networks_library.urls")),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password-reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password-change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # path('projects/', include('project.urls'))
]

project/urls.py
""" импорт модулей """

from django.urls import path

from .views import (
    ProjectsListView,
    ProjectDetailView,
    ProjectEditView,
    ProjectDeleteView,
    ProjectCreateView,
    index,
)

app_name = "project"

urlpatterns = (
    path("", index, name="index"),
    path("projects/", ProjectsListView.as_view(), name="projects"),
    path("project/<int:pk>", ProjectDetailView.as_view(), name="project_detail"),
    path("project/edit/<int:pk>", ProjectEditView.as_view(), name="project_edit"),
    path(
        "project/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"
    ),
    path("project/create/", ProjectCreateView.as_view(), name="project-create"),
)

project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q

# Create your models here.


class Projects(models.Model):
    project_name = models.CharField(max_length=50, unique=True)
    project_description = models.CharField(max_length=250, blank=True, null=True)
    users = models.ManyToManyField(User, related_name="users")
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="project_author"
    )
    updated_on = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def user_has_access(self, user):
        return (
            user == self.created_by
            or Projects.objects.filter(
                Q(created_by=user) | Q(users=user), pk=self.pk
            ).exists()
        )

    def user_has_access_delete(self, user):
        return user == self.created_by

    def __str__(self):
        return str(self.project_name)

project/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Projects


class ProjectEditForm(forms.ModelForm):
    class Meta:
        model = Projects
        fields = ["project_name", "project_description", "users"]
        labels = {
            "project_name": "Название проекта",
            "project_description": "Описание проекта",
            "users": "Пользователи у которых будет доступ к проекту",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["users"].widget = forms.CheckboxSelectMultiple()
        self.fields["users"].required = False
        self.fields["users"].queryset = User.objects.all()
        self.fields["users"].queryset = User.objects.exclude(
            pk=self.instance.created_by.pk
        )


class ProjectCreateForm(forms.ModelForm):
    class Meta:
        model = Projects
        fields = ["project_name", "project_description", "users"]
        labels = {
            "project_name": "Название проекта",
            "project_description": "Описание проекта",
            "users": "Пользователи, у которых будет доступ к проекту",
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")  # Получаем пользователя из kwargs
        super().__init__(*args, **kwargs)
        self.fields["users"].required = False
        self.fields["users"].widget = forms.CheckboxSelectMultiple()
        self.fields["users"].queryset = User.objects.exclude(pk=self.user.pk)

    def clean_project_name(self):
        project_name = self.cleaned_data["project_name"]
        if Projects.objects.filter(project_name=project_name).exists():
            self.add_error(
                "project_name",
                "Проект с таким названием уже существует. Измените наименование проекта",
            )
        return project_name

project/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
    CreateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from project.models import Projects
from .forms import ProjectCreateForm, ProjectEditForm


# Create your views here.


class ProjectAccessMixin:
    def get_object(self):
        obj = get_object_or_404(Projects, pk=self.kwargs["pk"])
        if not obj.user_has_access(
            self.request.user
        ):  # Добавьте вашу логику проверки доступа здесь
            raise PermissionDenied("У вас нет доступа к этому проекту.")
        return obj


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Projects
    form_class = ProjectCreateForm
    template_name = "project/project_create.html"
    success_url = reverse_lazy("project:projects")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user  # Передаем текущего пользователя в форму
        return kwargs


class ProjectsListView(LoginRequiredMixin, ProjectAccessMixin, ListView):
    login_url = "/login/"
    model = Projects
    template_name = "project/projects_list.html"
    context_object_name = "projects"

    def get_queryset(self):
        user = self.request.user
        return Projects.objects.filter(users=user) | Projects.objects.filter(
            created_by=user
        )


class ProjectDetailView(LoginRequiredMixin, ProjectAccessMixin, DetailView):
    login_url = "/login/"
    model = Projects
    template_name = "project/project_detail.html"
    context_object_name = "project"


class ProjectEditView(LoginRequiredMixin, ProjectAccessMixin, UpdateView):
    model = Projects
    form_class = ProjectEditForm
    template_name = "project/project_edit.html"
    success_url = reverse_lazy("project:projects")


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model = Projects
    success_url = reverse_lazy("project:projects")
    template_name = "project/project_confirm_delete.html"

    def get_object(self, queryset=None):
        # Получаем объект проекта
        obj = super().get_object(queryset)
        # Проверяем, имеет ли текущий пользователь право на удаление проекта
        if not obj.user_has_access_delete(self.request.user):
            # Если у пользователя нет доступа к проекту для удаления, возбуждаем 403 ошибку
            raise PermissionDenied("У вас нет прав для удаления этого проекта.")
        return obj

    def get_success_url(self):
        return reverse_lazy("project:projects")


def custom_permission_denied(request, exception):
    return render(request, "403.html", status=403)


def custom_page_not_found(request, exception):
    return render(request, "404.html", status=404)


def index(request):
    "return index.html"
    return render(request, "project/index.html")

project/templates/project/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
  <h1>Hello from projects index html</h1>
  {% if user.is_authenticated %}
    <p>privite text should be hidden</p>
  {% endif %}
{% endblock %}

project/templates/project/project_confirm_delete.html
{% extends "base.html" %}

{% block main %}
    <h2 class="text-center mt-5 mb-5">Вы уверены что хотите удалить проект?</h2>
    <form method="post" class="text-center">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Подтвердить удаление</button>
        <a href="{% url 'project:projects' %}" class="btn btn-danger" type="button">Отменить удаление</a>
    </form>

{% endblock main %}

project/templates/project/project_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block main %}
    <div class="col-6 mt-5">
        <div class="row text-center"><h2>Создать проект</h2></div>

        <form method="post" class="mt-3 mb-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
            <button type="button" class="btn btn-light"><a href="{% url 'project:projects' %}">Отменить</a></button>
        </form>

    </div>

{% endblock main %}

project/templates/project/project_detail.html
{% extends "base.html" %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>{{ project.project_name | escape }}</h1>
                <p class="lead">Описание: {{ project.project_description | escape }}</p>
                <p>Создан: {{ project.created_on }}</p>
                <p>Изменен: {{ project.updated_on }}</p>
                <p>Автор: {{ project.created_by }}</p>
                <h3>Пользователи проекта:</h3>
                <ul>
                    {% for user in project.users.all %}
                        <li>{{ user.username | escape }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-6">
                <div class="btn-group" role="group" aria-label="Управление проектом">
                    <a href="{% url 'project:project_edit' pk=project.pk %}" class="btn btn-primary">Изменить</a>
                    <a href="{% url 'project:project-delete' project.pk %}" class="btn btn-danger">Удалить</a>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

project/templates/project/project_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <div class="container">
        <h2>Редактирование проекта</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="row mt-4">
                <div class="col-md-6">
                    <div class="btn-group" role="group" aria-label="Управление проектом">
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a href="{% url 'project:projects' %}" class="btn btn-danger">Отменить</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

project/templates/project/projects_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block main %}
<h1>Мои проекты:</h1>
<div class="row">
    {% for project in object_list %}
    <div class="col-md-6">
        <div class="card m-3">
            <div class="card-body">
                <h5 class="card-title">{{ project.project_name | escape }}</h5>
                <p class="card-text">{{ project.project_description | escape }}</p>
                <p class="card-text"><small class="text-muted">Автор: {{ project.created_by | escape }}</small></p>
                <p class="card-text"><small class="text-muted">Изменено: {{ project.updated_on }}</small></p>
                <a href="{% url 'project:project_detail' pk=project.pk %}" class="btn btn-primary">Подробно</a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>
<a class="btn btn-primary" href="{% url 'project:project-create' %}" role="button">Создать проект</a>
{% endblock main %}