heat_networks_library/urls.py
""" импорт модулей """

from django.urls import path
from .views import index, HeatNetworksLibraryListView, PipeCreateView

app_name = "heat_networks_library"

urlpatterns = [
    # path("", index, name="index"),
    path("", HeatNetworksLibraryListView.as_view(), name="index"),
    path("add-pipe/", PipeCreateView.as_view(), name="add_pipe"),
]

ovhomelab/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views
from project.views import custom_page_not_found
from project.views import custom_permission_denied

handler403 = custom_permission_denied
handler404 = custom_page_not_found

urlpatterns = [
    path("link-page/", admin.site.urls),
    path("", include("project.urls")),
    path("library_ts/", include("heat_networks_library.urls")),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password-reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password-change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # path('projects/', include('project.urls'))
]

project/urls.py
""" импорт модулей """

from django.urls import path

from .views import (
    ProjectsListView,
    ProjectDetailView,
    ProjectEditView,
    ProjectDeleteView,
    ProjectCreateView,
    index,
)

app_name = "project"

urlpatterns = (
    path("", index, name="index"),
    path("projects/", ProjectsListView.as_view(), name="projects"),
    path("project/<int:pk>", ProjectDetailView.as_view(), name="project_detail"),
    path("project/edit/<int:pk>", ProjectEditView.as_view(), name="project_edit"),
    path(
        "project/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"
    ),
    path("project/create/", ProjectCreateView.as_view(), name="project-create"),
)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <title>Django Authentication Example</title>
</head>

<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'project:index' %}">Ovhomelab</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span
            class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse container-fluid justify-content-between" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'project:projects' %}">Проекты</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Калькулятор</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Библиотека</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'heat_networks_library:index' %}">Тепловые сети</a></li>
                <li><a class="dropdown-item" href="#">Отопление</a></li>
                <li><a class="dropdown-item" href="#">Вентиляция</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Кондиционирование</a></li>
              </ul>
            </li>
            {% if user.is_authenticated and user.is_superuser %}
              <a class="nav-link" href="{% url 'admin:index' %}">Административная панель</a>
            {% endif %}
          </ul>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="nav-link disabled">User: {{ user.get_username }}</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="col-12">
        {% block main %}

        {% endblock %}
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>

</html>